# Generated by Django 3.0.6 on 2020-05-30 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReport', models.DateField(default=datetime.date(2000, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='StatusScooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassisNumber', models.IntegerField(max_length=10)),
                ('deliveryman', models.CharField(max_length=200)),
                ('observation', models.CharField(max_length=500)),
                ('pickUpTime', models.TimeField()),
                ('returnTime', models.TimeField()),
                ('helmet', models.BooleanField()),
                ('bags', models.BooleanField()),
                ('charger', models.BooleanField()),
                ('case', models.BooleanField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StatusScooter')),
            ],
        ),
    ]
