# Generated by Django 3.0.6 on 2020-05-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movement_ol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassisNumber', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='chassisNumber',
        ),
        migrations.AddField(
            model_name='movement',
            name='scooter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Scooter'),
        ),
    ]
