# Generated by Django 3.0.4 on 2020-05-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200530_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='status',
        ),
        migrations.AddField(
            model_name='scooter',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StatusScooter'),
        ),
    ]
