# Generated by Django 3.0.4 on 2020-05-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200530_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='OL',
        ),
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=True)),
                ('LogisticOperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LogisticOperator')),
            ],
        ),
        migrations.AlterField(
            model_name='movement',
            name='deliveryman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Deliveryman'),
        ),
    ]
