# Generated by Django 3.0.4 on 2020-05-31 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200531_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='LogisticOperator',
        ),
        migrations.AddField(
            model_name='movement',
            name='logisticOperator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LogisticOperator'),
        ),
    ]
