# Generated by Django 3.0.4 on 2020-06-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200531_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='case',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='charger',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='helmet',
        ),
        migrations.AddField(
            model_name='movement',
            name='accessoriesBag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movement',
            name='accessoriesCase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movement',
            name='accessoriesCharger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movement',
            name='accessoriesHelmet',
            field=models.BooleanField(default=False),
        ),
    ]
