# Generated by Django 3.0.4 on 2020-06-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_deliveryman_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='observation',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
