# Generated by Django 3.0.4 on 2020-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_movement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='logisticoperator',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='chassisNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
