# Generated by Django 3.0.4 on 2020-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200606_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticoperator',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
