# Generated by Django 3.0.4 on 2020-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200606_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='chassisNumber',
            field=models.IntegerField(),
        ),
    ]
