# Generated by Django 3.0.4 on 2020-06-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200606_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='logisticOperator',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='logisticOperator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LogisticOperator'),
        ),
        migrations.AddField(
            model_name='movement',
            name='logisticOperatorDescription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
