# Generated by Django 3.0.4 on 2020-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200608_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='dateMovement',
        ),
        migrations.AddField(
            model_name='movement',
            name='finalDateMovement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='intialDateMovement',
            field=models.DateField(null=True),
        ),
    ]
