# Generated by Django 3.0.4 on 2020-06-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200613_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleregistration',
            name='active',
        ),
    ]
