# Generated by Django 3.0.4 on 2020-06-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_peopleregistration_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='peopleRegistration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PeopleRegistration'),
        ),
    ]
