# Generated by Django 3.0.4 on 2020-06-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200613_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleregistration',
            name='typePeople',
        ),
        migrations.DeleteModel(
            name='TypePeople',
        ),
    ]
